"""Fix Team-PlayerScore relationship

Revision ID: 08a5bcaa525b
Revises: 3fce1202b504
Create Date: 2025-04-14 17:06:59.943764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a5bcaa525b'
down_revision: Union[str, None] = '3fce1202b504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_scores', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_scores', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_scores', type_='foreignkey')
    op.drop_column('player_scores', 'team_id')
    # ### end Alembic commands ###
