"""Remove static number_of_weeks from league

Revision ID: 0ff238a1d130
Revises: ad41db258c2a
Create Date: 2025-04-14 18:40:22.661733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ff238a1d130'
down_revision: Union[str, None] = 'ad41db258c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'number_of_weeks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('number_of_weeks', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
