"""Fix base model imports

Revision ID: 5ecfe151da0c
Revises: eee99e41ee2a
Create Date: 2025-04-14 17:23:37.274238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ecfe151da0c'
down_revision: Union[str, None] = 'eee99e41ee2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_id', table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hole_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strokes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_played', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='scores_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_scores_id', 'scores', ['id'], unique=False)
    # ### end Alembic commands ###
