"""Update match and scoring models

Revision ID: 933784b20763
Revises: 24ed8a51fc91
Create Date: 2025-04-13 16:08:39.261057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '933784b20763'
down_revision: Union[str, None] = '24ed8a51fc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hole_scores', sa.Column('hole_id', sa.Integer(), nullable=True))
    op.add_column('hole_scores', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'hole_scores', 'holes', ['hole_id'], ['id'])
    op.drop_column('hole_scores', 'hole_number')
    op.alter_column('leagues', 'start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('matches', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.add_column('player_scores', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('player_scores_ibfk_3', 'player_scores', type_='foreignkey')
    op.drop_column('player_scores', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_scores', sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('player_scores_ibfk_3', 'player_scores', 'teams', ['team_id'], ['id'])
    op.drop_column('player_scores', 'created_at')
    op.alter_column('matches', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('leagues', 'start_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.add_column('hole_scores', sa.Column('hole_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hole_scores', type_='foreignkey')
    op.drop_column('hole_scores', 'created_at')
    op.drop_column('hole_scores', 'hole_id')
    # ### end Alembic commands ###
