"""Add holes table

Revision ID: aaacf43a7979
Revises: 145f42eda3ee
Create Date: 2025-04-12 22:42:42.429271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaacf43a7979'
down_revision: Union[str, None] = '145f42eda3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'holes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('holes', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
